# BEGIN SUBSTITUTIONS
# Borrowed or shamelessly stolen frok Athom tech github
substitutions:
  name: "put your device name in here"
  friendly_name: "esp32 sprinkler controller"
  # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc
  device_description: "esp32 sprinkler controller"
  sensor_update_interval: "10s"
  # Set timezone of the smart plug. Useful if the plug is in a location different to the HA server. Can be entered in unix Country/Area format (i.e. "Australia/Sydney")
  timezone: "Enter your local timezone here"  # (ex America\Winnipeg)
  # Set the duration between the sntp service polling ntp.org servers for an update
  sntp_update_interval: "6h"
  # Network time servers for your region, enter from lowest to highest priority. To use local servers update as per zones or countries at: https://www.ntppool.org/zone/@
  sntp_server_1: "enter primary local ntp server address here"
  sntp_server_2: "enter secondary local ntp server address here"
  # Enables faster network connections, with last connected SSID being connected to and no full scan for SSID being undertaken
  wifi_fast_connect: "false"
  # Define logging level: NONE, ERROR, WARN, INFO, DEBUG (Default), VERBOSE, VERY_VERBOSE
  log_level: "INFO"
  # Enable or disable the use of IPv6 networking on the device
  ipv6_enable: "false"

# BEGIN ESPHOME
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: ${device_description}
  name_add_mac_suffix: false
  min_version: 2025.9.0

# BEGIN ESP
esp32:
  variant: esp32
  framework:
    type: esp-idf

# BEGIN SENSOR
sensor:

# BEGIN PLATFORM SENSORS
# This will give us values and entities in HA
  - platform: uptime
    name: "Uptime Sensor"
    id: uptime_sensor
    entity_category: diagnostic
    internal: true

  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: ${sensor_update_interval}
    entity_category: "diagnostic"

  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""

# BEGIN TEXT SENSORS
# This will give us entities in HA
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "WiFi IP Address"
      entity_category: diagnostic
    ssid:
      name: "WiFi Connected SSID"
      entity_category: diagnostic
    mac_address:
      name: "WiFi Mac Address"
      entity_category: diagnostic

# BEGIN BINARY SENSORS
binary_sensor:
  - platform: status
    name: "Status"

# BEGIN Switching
# each switch is configured high to pull low on activations. 
#interlock makes sure that multiple zones aren't running at once (water pressure dependent)
switch:
  - platform: gpio
    pin:
      number: GPIO32
      inverted: true
    name: "Backyard Sprinklers Zone 1"
    icon: "mdi:sprinkler-variant"
    id: relay1
    interlock: [relay2, relay3, relay4, relay5, relay6, relay7, relay8]
  - platform: gpio
    pin:
      number: GPIO21
      inverted: true
    id: relay2
    name: "Backyard Sprinklers Zone 2"
    icon: "mdi:sprinkler-variant"
    interlock: [relay1, relay3, relay4, relay5, relay6, relay7, relay8]
  - platform: gpio
    pin:
      number: GPIO27
      inverted: true
    id: relay3
    name: "Backyard Sprinklers Zone 3"
    icon: "mdi:sprinkler-variant"
    interlock: [relay1, relay2, relay4, relay5, relay6, relay7, relay8]
  - platform: gpio
    pin:
      number: GPIO22
      inverted: true
    id: relay4
    name: "Backyard Sprinklers Zone 4"
    icon: "mdi:sprinkler-variant"
    interlock: [relay1, relay2, relay3, relay5, relay6, relay7, relay8]
  - platform: gpio
    pin:
      number: GPIO23
      inverted: true
    id: relay5
    name: "Frontyard Sprinklers Zone 1"
    icon: "mdi:sprinkler-variant"
    interlock: [relay1, relay2, relay3, relay4, relay6, relay7, relay8]
  - platform: gpio
    pin:
      number: GPIO26
      inverted: true
    id: relay6
    name: "Frontyard Sprinklers Zone 2"
    icon: "mdi:sprinkler-variant"
    interlock: [relay1, relay2, relay3, relay4, relay5, relay7, relay8]
  - platform: gpio
    pin:
      number: GPIO25
      inverted: true
    id: relay7
    name: "Frontyard Sprinklers Zone 3"
    icon: "mdi:sprinkler-variant"
    interlock: [relay1, relay2, relay3, relay4, relay5, relay6, relay8]
  - platform: gpio
    pin:
      number: GPIO33
      inverted: true
    id: relay8
    name: "Frontyard Sprinklers Zone 4"
    icon: "mdi:sprinkler-variant"
    interlock: [relay2, relay3, relay4, relay5, relay6, relay7, relay1]

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Webserver
web_server:  
  port: 80

# WiFi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
